import { motion, useInView } from "framer-motion";
import { useRef, useState } from "react";
import { Github, ExternalLink, ArrowUpRight } from "lucide-react";

type Project = {
  title: string;
  description: string;
  tags: string[];
  github: string;
  repo: string; // owner/repo for live GitHub preview
  year: string;
  role: string;
};

const projects: Project[] = [
  {
    title: "College Lost and Found System",
    description:
      "A web platform that helps students and staff report, track, and recover lost items across the campus with real-time updates and an effortless claim workflow.",
    tags: ["React", "TypeScript", "Tailwind", "Supabase"],
    github: "https://github.com/selva816453/college-lost-and-found-system",
    repo: "selva816453/college-lost-and-found-system",
    year: "2025",
    role: "Full-stack",
  },
  {
    title: "E-Commerce Grocery Website",
    description:
      "A responsive grocery e-commerce experience featuring a product catalog, dynamic shopping cart, and smooth browsing across devices.",
    tags: ["HTML", "CSS", "JavaScript", "Responsive"],
    github: "https://github.com/selva816453/Grocery-website-clone",
    repo: "selva816453/Grocery-website-clone",
    year: "2024",
    role: "Frontend",
  },
  {
    title: "Unauthorized Person Detection",
    description:
      "An AI-powered surveillance solution that detects and flags unauthorized individuals in restricted areas using computer vision and face recognition.",
    tags: ["Python", "OpenCV", "Deep Learning", "Face Recognition"],
    github: "https://github.com/selva816453/UnauthorizedPerson_Detection_System",
    repo: "selva816453/UnauthorizedPerson_Detection_System",
    year: "2024",
    role: "ML / Vision",
  },
];

// Live GitHub OpenGraph preview — regenerated by GitHub from the actual repo
const livePreview = (repo: string) =>
  `https://opengraph.githubassets.com/${Date.now()}/${repo}`;

const ProjectsSection = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });
  const [active, setActive] = useState(0);

  return (
    <section id="projects" className="section-padding relative overflow-hidden">
      <div className="blur-orb w-[500px] h-[500px] bg-primary/10 -top-40 right-0" />
      <div className="blur-orb w-[400px] h-[400px] bg-secondary/10 bottom-0 left-1/4" />

      <div className="container-custom relative z-10 px-5 sm:px-6 lg:px-16" ref={ref}>
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="mb-10 md:mb-14 flex flex-col md:flex-row md:items-end md:justify-between gap-4"
        >
          <div>
            <p className="text-xs sm:text-sm font-mono text-secondary tracking-[0.3em] mb-3">
              // SELECTED.WORK
            </p>
            <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold text-foreground">
              Projects<span className="text-secondary">.</span>
            </h2>
          </div>
          <p className="text-muted-foreground text-sm md:text-base font-mono max-w-sm">
            Live previews fetched in real time from GitHub.
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-[1fr_1.2fr] gap-6 lg:gap-10 items-start">
          {/* LEFT: index list */}
          <div className="space-y-3">
            {projects.map((p, i) => {
              const isActive = i === active;
              return (
                <motion.button
                  key={p.title}
                  onClick={() => setActive(i)}
                  initial={{ opacity: 0, x: -20 }}
                  animate={isInView ? { opacity: 1, x: 0 } : {}}
                  transition={{ duration: 0.4, delay: i * 0.08 }}
                  className={`w-full text-left p-4 sm:p-5 rounded-2xl border backdrop-blur-xl transition-all duration-300 group ${
                    isActive
                      ? "border-secondary/60 bg-card/60 shadow-[0_0_30px_-10px_hsl(var(--secondary)/0.5)]"
                      : "border-border/40 bg-card/20 hover:border-border hover:bg-card/40"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <span className="text-[10px] sm:text-xs font-mono text-muted-foreground tracking-widest">
                      0{i + 1} · {p.year} · {p.role}
                    </span>
                    <ArrowUpRight
                      className={`w-4 h-4 transition-all ${
                        isActive
                          ? "text-secondary translate-x-0 translate-y-0"
                          : "text-muted-foreground group-hover:text-secondary"
                      }`}
                    />
                  </div>
                  <h3
                    className={`text-base sm:text-lg md:text-xl font-bold leading-tight mb-2 transition-colors ${
                      isActive ? "text-foreground" : "text-foreground/80"
                    }`}
                  >
                    {p.title}
                  </h3>
                  {isActive && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <p className="text-muted-foreground text-xs sm:text-sm leading-relaxed mt-2">
                        {p.description}
                      </p>
                      <div className="flex flex-wrap gap-1.5 mt-3">
                        {p.tags.map((t) => (
                          <span
                            key={t}
                            className="text-[10px] font-mono px-2 py-1 rounded-md bg-primary/10 text-primary border border-primary/20"
                          >
                            {t}
                          </span>
                        ))}
                      </div>
                    </motion.div>
                  )}
                </motion.button>
              );
            })}
          </div>

          {/* RIGHT: live preview window */}
          <motion.div
            key={active}
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4 }}
            className="lg:sticky lg:top-24"
          >
            <div className="relative rounded-2xl overflow-hidden border border-border/50 bg-card/40 backdrop-blur-xl shadow-2xl">
              {/* Terminal-style chrome */}
              <div className="flex items-center gap-2 px-4 py-3 border-b border-border/40 bg-background/40">
                <span className="w-3 h-3 rounded-full bg-red-500/70" />
                <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
                <span className="w-3 h-3 rounded-full bg-green-500/70" />
                <span className="ml-3 text-[11px] font-mono text-muted-foreground truncate">
                  github.com/{projects[active].repo}
                </span>
                <span className="ml-auto flex items-center gap-1.5 text-[10px] font-mono text-green-400/80">
                  <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                  LIVE
                </span>
              </div>

              {/* Live GitHub OG preview */}
              <div className="relative aspect-[120/63] bg-background/60 overflow-hidden">
                <div className="absolute -inset-6 bg-gradient-to-br from-primary/20 to-secondary/20 blur-3xl opacity-60" />
                <img
                  key={projects[active].repo}
                  src={livePreview(projects[active].repo)}
                  alt={`${projects[active].title} — live GitHub preview`}
                  loading="lazy"
                  className="relative w-full h-full object-cover"
                />
              </div>

              <div className="flex items-center justify-between gap-3 px-4 py-3 border-t border-border/40 bg-background/40">
                <span className="text-[11px] font-mono text-muted-foreground">
                  Auto-refreshed from repo
                </span>
                <div className="flex gap-2">
                  <motion.a
                    href={projects[active].github}
                    target="_blank"
                    rel="noopener noreferrer"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.97 }}
                    className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-secondary text-secondary-foreground text-xs font-semibold"
                  >
                    <Github className="w-3.5 h-3.5" />
                    Code
                    <ExternalLink className="w-3 h-3" />
                  </motion.a>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default ProjectsSection;
